/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Event {
  'id' : bigint,
  'title' : string,
  'date' : string,
  'createdAt' : bigint,
  'description' : string,
  'isActive' : boolean,
  'imageUrl' : string,
  'category' : string,
  'location' : string,
}
export interface EventStats {
  'avgOrganizationRating' : number,
  'avgOverallRating' : number,
  'totalCount' : bigint,
  'avgContentRating' : number,
  'recommendRate' : number,
  'avgVenueRating' : number,
}
export interface Feedback {
  'id' : bigint,
  'eventId' : bigint,
  'submitterName' : string,
  'submittedAt' : bigint,
  'venueRating' : bigint,
  'comment' : string,
  'organizationRating' : bigint,
  'overallRating' : bigint,
  'contentRating' : bigint,
  'submitterEmail' : string,
  'wouldRecommend' : boolean,
}
export interface OverallStats {
  'avgOverallRating' : number,
  'totalEvents' : bigint,
  'recommendRate' : number,
  'totalFeedback' : bigint,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createEvent' : ActorMethod<
    [string, string, string, string, string, string, boolean],
    undefined
  >,
  'deleteEvent' : ActorMethod<[bigint], undefined>,
  'deleteFeedback' : ActorMethod<[bigint], undefined>,
  'getActiveEvents' : ActorMethod<[], Array<Event>>,
  'getAllEvents' : ActorMethod<[], Array<Event>>,
  'getAllFeedback' : ActorMethod<[], Array<Feedback>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getEvent' : ActorMethod<[bigint], Event>,
  'getEventStats' : ActorMethod<[bigint], EventStats>,
  'getFeedbackByEvent' : ActorMethod<[bigint], Array<Feedback>>,
  'getOverallStats' : ActorMethod<[], OverallStats>,
  'getRecentFeedback' : ActorMethod<[bigint], Array<Feedback>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitFeedback' : ActorMethod<
    [bigint, string, string, bigint, bigint, bigint, bigint, string, boolean],
    undefined
  >,
  'updateEvent' : ActorMethod<
    [bigint, string, string, string, string, string, string, boolean],
    undefined
  >,
  'verifyAdminPin' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];