/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Event = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'date' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
  'location' : IDL.Text,
});
export const Feedback = IDL.Record({
  'id' : IDL.Nat,
  'eventId' : IDL.Nat,
  'submitterName' : IDL.Text,
  'submittedAt' : IDL.Int,
  'venueRating' : IDL.Nat,
  'comment' : IDL.Text,
  'organizationRating' : IDL.Nat,
  'overallRating' : IDL.Nat,
  'contentRating' : IDL.Nat,
  'submitterEmail' : IDL.Text,
  'wouldRecommend' : IDL.Bool,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const EventStats = IDL.Record({
  'avgOrganizationRating' : IDL.Float64,
  'avgOverallRating' : IDL.Float64,
  'totalCount' : IDL.Nat,
  'avgContentRating' : IDL.Float64,
  'recommendRate' : IDL.Float64,
  'avgVenueRating' : IDL.Float64,
});
export const OverallStats = IDL.Record({
  'avgOverallRating' : IDL.Float64,
  'totalEvents' : IDL.Nat,
  'recommendRate' : IDL.Float64,
  'totalFeedback' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createEvent' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
      [],
      [],
    ),
  'deleteEvent' : IDL.Func([IDL.Nat], [], []),
  'deleteFeedback' : IDL.Func([IDL.Nat], [], []),
  'getActiveEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
  'getAllEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
  'getAllFeedback' : IDL.Func([], [IDL.Vec(Feedback)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEvent' : IDL.Func([IDL.Nat], [Event], ['query']),
  'getEventStats' : IDL.Func([IDL.Nat], [EventStats], ['query']),
  'getFeedbackByEvent' : IDL.Func([IDL.Nat], [IDL.Vec(Feedback)], ['query']),
  'getOverallStats' : IDL.Func([], [OverallStats], ['query']),
  'getRecentFeedback' : IDL.Func([IDL.Nat], [IDL.Vec(Feedback)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitFeedback' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Bool,
      ],
      [],
      [],
    ),
  'updateEvent' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Bool,
      ],
      [],
      [],
    ),
  'verifyAdminPin' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Event = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'date' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
    'location' : IDL.Text,
  });
  const Feedback = IDL.Record({
    'id' : IDL.Nat,
    'eventId' : IDL.Nat,
    'submitterName' : IDL.Text,
    'submittedAt' : IDL.Int,
    'venueRating' : IDL.Nat,
    'comment' : IDL.Text,
    'organizationRating' : IDL.Nat,
    'overallRating' : IDL.Nat,
    'contentRating' : IDL.Nat,
    'submitterEmail' : IDL.Text,
    'wouldRecommend' : IDL.Bool,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const EventStats = IDL.Record({
    'avgOrganizationRating' : IDL.Float64,
    'avgOverallRating' : IDL.Float64,
    'totalCount' : IDL.Nat,
    'avgContentRating' : IDL.Float64,
    'recommendRate' : IDL.Float64,
    'avgVenueRating' : IDL.Float64,
  });
  const OverallStats = IDL.Record({
    'avgOverallRating' : IDL.Float64,
    'totalEvents' : IDL.Nat,
    'recommendRate' : IDL.Float64,
    'totalFeedback' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createEvent' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
        [],
        [],
      ),
    'deleteEvent' : IDL.Func([IDL.Nat], [], []),
    'deleteFeedback' : IDL.Func([IDL.Nat], [], []),
    'getActiveEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
    'getAllEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
    'getAllFeedback' : IDL.Func([], [IDL.Vec(Feedback)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEvent' : IDL.Func([IDL.Nat], [Event], ['query']),
    'getEventStats' : IDL.Func([IDL.Nat], [EventStats], ['query']),
    'getFeedbackByEvent' : IDL.Func([IDL.Nat], [IDL.Vec(Feedback)], ['query']),
    'getOverallStats' : IDL.Func([], [OverallStats], ['query']),
    'getRecentFeedback' : IDL.Func([IDL.Nat], [IDL.Vec(Feedback)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitFeedback' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Bool,
        ],
        [],
        [],
      ),
    'updateEvent' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Bool,
        ],
        [],
        [],
      ),
    'verifyAdminPin' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };